sudo: enabled

before_install:
        - sudo apt-get update && sudo apt-get -y install make gcc-aarch64-linux-gnu qemu-system-arm gdb-multiarch tmux

language: bash

script:
        make PLAT=qemu
        timeout 10 make ci > test.run || true
        grep "Success" test.run
