sudo: enabled

before_install:
        - sudo apt-get update && sudo apt-get -y install astyle make gcc-arm-none-eabi qemu-system-arm gdb-multiarch tmux

language: bash

script:
        - git diff --name-only $TRAVIS_COMMIT_RANGE \ 
            | ( grep '.\(c\|cpp\|h\|hpp\)$' || true ) \
            | ( fgrep -v -f .astyleignore || true ) \
            | while read file; do astyle -n --options=.astylerc "${file}"; done
        - make PLAT=qemu
        - timeout --foreground 5 qemu-system-arm -d guest_errors -M lm3s811evb -m 8K -nographic -kernel main.elf > test.run || true
        - cat test.run
        - grep "Success" test.run

